# Project: ElevatorManagement
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o PriorityQueue.o Elevator.o Display.o Performance.o
LINKOBJ  = main.o PriorityQueue.o Elevator.o Display.o Performance.o
LIBS     = -L"D:/VanPhuc/App/Dev-Cpp/MinGW64/lib" -L"D:/VanPhuc/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/VanPhuc/App/Dev-Cpp/MinGW64/include" -I"D:/VanPhuc/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/VanPhuc/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/VanPhuc/App/Dev-Cpp/MinGW64/include" -I"D:/VanPhuc/App/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/VanPhuc/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/VanPhuc/App/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ElevatorManagement.exe
CXXFLAGS = $(CXXINCS) -std=c++11 -std=c++11
CFLAGS   = $(INCS) -std=c++11 -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

PriorityQueue.o: PriorityQueue.cpp
	$(CPP) -c PriorityQueue.cpp -o PriorityQueue.o $(CXXFLAGS)

Elevator.o: Elevator.cpp
	$(CPP) -c Elevator.cpp -o Elevator.o $(CXXFLAGS)

Display.o: Display.cpp
	$(CPP) -c Display.cpp -o Display.o $(CXXFLAGS)

Performance.o: Performance.cpp
	$(CPP) -c Performance.cpp -o Performance.o $(CXXFLAGS)
